services:

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - default-network
    depends_on:
      - api
      - wss
    ports:
      - "80:80"

  mongo:
    image: mongo
    volumes:
      - "mongodbdata:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    networks:
      - default-network

  api:
    image: 177973969841.dkr.ecr.us-east-1.amazonaws.com/peddl-api-${ENVIRONMENT:-staging}:${API_TAG:-latest}
    environment:
      NODE_ENV: ${ENVIRONMENT:-development}
      MONGO_DB: ${MONGO_DB}
      MONGO_URI: ${MONGO_URI}
      PORT: 8080
    volumes:
      - "mediadata:/srv/static"
    depends_on:
      - mongo
    networks:
      - default-network

  wss:
    image: 177973969841.dkr.ecr.us-east-1.amazonaws.com/peddl-wss-${ENVIRONMENT:-staging}:${WSS_TAG:-latest}
    environment:
      NODE_ENV: ${ENVIRONMENT:-development}
      MONGO_DB: ${MONGO_DB}
      MONGO_URI: ${MONGO_URI}
      PORT: 8000
    depends_on:
      - mongo
    networks:
      - default-network

networks:
  default-network: {}
volumes:
  mongodbdata:
  mediadata:
