name: 'API Pipeline'
on:
  push:
    branches:
      - staging
    paths:
      - packages/api/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: ./.github/workflows/build.yml
        with:
          project: api
