name: 'API staging'
on:
  push:
    branches:
      - staging
    paths:
      - packages/api/**

jobs:
  build:
    environment: staging
    uses: ./.github/workflows/build.yml
    with:
      project: api
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
