name: 'API Pipeline'
on:
  push:
    branches:
      - staging
    paths:
      - packages/api/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push to ECR
        uses: ./.github/workflows/build.yml
        with:
          project: api
