name: 'Build'
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
    secrets: inherit

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker build
        run: docker build -t peddl-${{ inputs.project }}:${{ github.sha }} --build-arg BUILD_CONTEXT=${{ inputs.project }} .

      - name: Docker tag
        run: docker tag peddl-${{ inputs.project }}:${{ github.sha }} 177973969841.dkr.ecr.us-east-1.amazonaws.com/peddl-${{ inputs.project }}:${{ github.sha }}

      - name: Docker push
        run: docker push 177973969841.dkr.ecr.us-east-1.amazonaws.com/peddl-${{ inputs.project }}:${{ github.sha }}
