name: '[Staging] Build & deploy API'
on:
  push:
    paths:
      - packages/api/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build --build-arg BUILD_CONTEXT=api .
