name: '[Staging] Build & deploy API'
on:
  push:
    branches:
      - staging
    paths:
      - packages/api/**
jobs:
  build:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: satackey/action-docker-layer-caching@v0.0.11
      - run: docker build --build-arg BUILD_CONTEXT=api .
