name: 'UI Workflow'

on:
  push:
    branches:
      - staging
    paths:
      - packages/ui/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Yarn v3
        run: corepack enable && yarn set version 3.2.3

      - name: Install deps
        run: yarn

      - name: Build common
        run: yarn common build

      - name: Build UI
        run: yarn ui build

      - name: Sync with S3 bucket
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'packages/ui/build'

