name: 'WSS Workflow'

on:
  push:
    branches:
      - main
    paths:
      - packages/wss/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push to ECR
        uses: ./.github/actions/build
        with:
          environment: staging
          project: wss
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to EC2
        uses: ./.github/actions/deploy
        with:
          environment: staging
          project: wss
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ip_address: ${{ secrets.IP_ADDRESS }}
          mongo_root_username: ${{ secrets.MONGO_ROOT_USERNAME }}
          mongo_root_password: ${{ secrets.MONGO_ROOT_PASSWORD }}
          mongo_db: ${{ secrets.MONGO_DB }}
          mongo_uri: ${{ secrets.MONGO_URI }}
