name: 'API Workflow'

on:
  push:
    branches:
      - staging
    paths:
      - packages/wss/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push to ECR
        uses: ./.github/actions/build
        with:
          project: wss
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
